package baritone.api.process;
public enum PathingCommandType {
    REQUEST_PAUSE, DEFER, FORCE_REVALIDATE_GOAL_AND_PATH, REVALIDATE_GOAL_AND_PATH, SET_GOAL_AND_PATH, CANCEL_AND_SET_GOAL, REQUEST_PAUSE_SAFE;
}
